Fix Fatal Error detection.
the output of IAR 6.4 compiler is as followed:

SystemService.c 
Fatal Error[Pe1696]: cannot open source file "c:\tmp\SystemService.c"
Error while running C/C++ Compiler
SystemTest.c 
c:\tmp\AdditionalResources.h(17) : Fatal Error[Pe1696]: cannot open source file "System/ProcDef_LPC17xx.h"
            searched: "c:\tmp\Src\"
Error while running C/C++ Compiler

I have put the name to  compiler version 6.X because 7 can give different output.